name: Tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        node: ['23']
        os: [ubuntu-24.04]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.os }}-${{ matrix.node }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm run build
      - run: npm run test
